FROM docker.io/library/alpine:latest

RUN apk add --no-cache ca-certificates tzdata

LABEL org.opencontainers.image.licenses=BSD-3-Clause
LABEL org.opencontainers.image.description="Paperless-ngx command line interface"

WORKDIR /

COPY LICENSE README.md /
COPY papercli /

ENTRYPOINT ["/papercli"]

# vim: set ft=dockerfile :
