# Configuration for GoReleaser
# https://goreleaser.com/
#
# Local test: contrib/build-all
#

version: 2

project_name: papercli

builds:
  - main: .
    binary: papercli
    env:
      - CGO_ENABLED=0
    targets:
      - go_first_class
    flags:
      - -trimpath

nfpms:
  - description: Paperless-ngx command line interface
    maintainer: M. Hanselmann
    bindir: /usr/bin
    license: BSD-3-Clause
    formats:
      - deb
      - rpm
    contents:
      - src: ./README.md
        dst: /usr/share/doc/papercli/README.md
      - src: ./LICENSE
        dst: /usr/share/doc/papercli/LICENSE

archives:
  - format: tar.gz
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md

dockers:
  - ids:
      - papercli
    use: buildx
    dockerfile: contrib/Dockerfile.goreleaser
    extra_files:
      - LICENSE
      - README.md
    image_templates:
      - ghcr.io/hansmi/papercli:{{.Tag}}
      - ghcr.io/hansmi/papercli:v{{.Major}}
      - ghcr.io/hansmi/papercli:latest
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}

release:
  draft: true
  prerelease: auto

snapshot:
  name_template: '{{ incpatch .Version }}-snapshot{{ replace (replace .Date ":" "") "-" "" }}+g{{ .ShortCommit }}'

# vim: set sw=2 sts=2 et :
